name: CI using maven and Jenkins
on:
  push:
  workflow_dispatch:
jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code on ubuntu server
        uses: actions/checkout@v4
      - name: Install Java and Maven on the ubuntu server
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"
          cache: 'maven'
      - name: Test the code3
        run: mvn test
      - name: Build the code
        run : mvn package
      - name: Get the artifact and upload on github repo
        uses: actions/upload-artifact@v4
        with:
          name: java-example-artiact
          path: /home/runner/work/MavenBuild-SL/MavenBuild-SL/target/java-example.war
      - name: connect to LAB and run curl command to trigger a job
        uses: cross-the-world/ssh-scp-ssh-pipeline@latest
        with:
          host: '13.235.80.17'
          user: 'labuser'
          pass: 'Nuvelabs123$'
          port: 22
          connect_timeout: 10s
          first_ssh:
            sudo curl -l -u admin:Root123$ http://localhost:8080/job/Build-Job/build?token=token1
          scp:
            '/.target/*.war => /tmp
          last_ssh:
            ls -al /tmp
